SELECT CAR_ID,
    CASE WHEN  START_DATE <= TO_DATE('2022-10-16', 'YYYY-MM-DD') AND END_DATE >= TO_DATE('2022-10-16', 'YYYY-MM-DD')THEN '대여중'
    ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE (CAR_ID, START_DATE) IN (
        SELECT CAR_ID, MAX(START_DATE)
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= TO_DATE('2022-10-16', 'YYYY-MM-DD')
        GROUP BY CAR_ID )
ORDER BY CAR_ID DESC;
