select  A.HOUR, NVL(B.COUNT,0) AS COUNT
from (
    SELECT LEVEL-1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL < 25
    ) A
LEFT JOIN(
    SELECT TO_CHAR(DATETIME, 'hh24') HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY TO_CHAR(DATETIME, 'hh24')
    ) B
    ON A.HOUR = B.HOUR
ORDER BY A.HOUR
